//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMMON.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMMON.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {s} is an invalid format.
        /// </summary>
        internal static string CExceptionInvalidFormat {
            get {
                return ResourceManager.GetString("CExceptionInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method {0} is not implemented inside object {1}.
        /// </summary>
        internal static string CExceptionNotImplemented {
            get {
                return ResourceManager.GetString("CExceptionNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is out of range.
        /// </summary>
        internal static string CExceptionOutOfRange {
            get {
                return ResourceManager.GetString("CExceptionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stream has been disconnected.
        /// </summary>
        internal static string CExceptionStreamDisconnected {
            get {
                return ResourceManager.GetString("CExceptionStreamDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EXCEPTION].
        /// </summary>
        internal static string CLogException {
            get {
                return ResourceManager.GetString("CLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string CLogExceptionFile {
            get {
                return ResourceManager.GetString("CLogExceptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line.
        /// </summary>
        internal static string CLogExceptionLine {
            get {
                return ResourceManager.GetString("CLogExceptionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method.
        /// </summary>
        internal static string CLogExceptionMethod {
            get {
                return ResourceManager.GetString("CLogExceptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string cannot be of zero length.
        /// </summary>
        internal static string CMiscCannotBeZeroLength {
            get {
                return ResourceManager.GetString("CMiscCannotBeZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid length - min length={0}; max length={1}; length={2}.
        /// </summary>
        internal static string CMiscCheckBufferMinMax {
            get {
                return ResourceManager.GetString("CMiscCheckBufferMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid length - value={3}; min length={0}; max length={1}; length={2}.
        /// </summary>
        internal static string CMiscCheckBufferMinMaxValue {
            get {
                return ResourceManager.GetString("CMiscCheckBufferMinMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid hexadecimal value.
        /// </summary>
        internal static string CMiscInvalidHexadecimalFormat {
            get {
                return ResourceManager.GetString("CMiscInvalidHexadecimalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid length (expecting {1}).
        /// </summary>
        internal static string CMiscInvalidLength {
            get {
                return ResourceManager.GetString("CMiscInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty list.
        /// </summary>
        internal static string CSafeListEmpty {
            get {
                return ResourceManager.GetString("CSafeListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempting to connect to {0}, timeout is {1} second(s).
        /// </summary>
        internal static string CStreamClientConnect {
            get {
                return ResourceManager.GetString("CStreamClientConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected to {0}.
        /// </summary>
        internal static string CStreamClientConnected {
            get {
                return ResourceManager.GetString("CStreamClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client failed to connect to {0}.
        /// </summary>
        internal static string CStreamClientNotConnected {
            get {
                return ResourceManager.GetString("CStreamClientNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endpoint: {0}; servername: {1}; allowed ssl errors: {2}.
        /// </summary>
        internal static string CStreamClientSettingsToString {
            get {
                return ResourceManager.GetString("CStreamClientSettingsToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding {0} bytes header.
        /// </summary>
        internal static string CStreamIOAddingHeader {
            get {
                return ResourceManager.GetString("CStreamIOAddingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificate error {0}.
        /// </summary>
        internal static string CStreamIOCertificateError {
            get {
                return ResourceManager.GetString("CStreamIOCertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client at {0} has been disconnected.
        /// </summary>
        internal static string CStreamIOClientDisconnected {
            get {
                return ResourceManager.GetString("CStreamIOClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data [{0}].
        /// </summary>
        internal static string CStreamIOData {
            get {
                return ResourceManager.GetString("CStreamIOData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expecting {0} bytes.
        /// </summary>
        internal static string CStreamIOExpectingBytes {
            get {
                return ResourceManager.GetString("CStreamIOExpectingBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed sending message of {0} bytes ({1}) to {2}.
        /// </summary>
        internal static string CStreamIOFailedSendingMessage {
            get {
                return ResourceManager.GetString("CStreamIOFailedSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed sending text message of {0} bytes to {2}.
        /// </summary>
        internal static string CStreamIOFailedSendingTextMessage {
            get {
                return ResourceManager.GetString("CStreamIOFailedSendingTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not adding header.
        /// </summary>
        internal static string CStreamIONotAddingHeader {
            get {
                return ResourceManager.GetString("CStreamIONotAddingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received announce for message of {0} bytes from {1}.
        /// </summary>
        internal static string CStreamIOReceiveAnnounceOf {
            get {
                return ResourceManager.GetString("CStreamIOReceiveAnnounceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received 0 bytes length announce from {0}.
        /// </summary>
        internal static string CStreamIOReceiveAnnounceOfZero {
            get {
                return ResourceManager.GetString("CStreamIOReceiveAnnounceOfZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received {0} bytes from {1}.
        /// </summary>
        internal static string CStreamIOReceivedMessage {
            get {
                return ResourceManager.GetString("CStreamIOReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received text message [{0}] from {1}.
        /// </summary>
        internal static string CStreamIOReceivedTextMessage {
            get {
                return ResourceManager.GetString("CStreamIOReceivedTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received un unexpected empty message from {0}.
        /// </summary>
        internal static string CStreamIOReceivedUnexpectedEmptyBuffer {
            get {
                return ResourceManager.GetString("CStreamIOReceivedUnexpectedEmptyBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting to receive a fixed sized buffer of {0} bytes from {1}.
        /// </summary>
        internal static string CStreamIOReceivingFixedSizeBuffer {
            get {
                return ResourceManager.GetString("CStreamIOReceivingFixedSizeBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chain element {0}: {1}.
        /// </summary>
        internal static string CStreamIOSecurityChainElement {
            get {
                return ResourceManager.GetString("CStreamIOSecurityChainElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending message of {0} bytes ({1}) to {2}.
        /// </summary>
        internal static string CStreamIOSendingMessage {
            get {
                return ResourceManager.GetString("CStreamIOSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending text message of {0} characters to {1}.
        /// </summary>
        internal static string CStreamIOSendingTextMessage {
            get {
                return ResourceManager.GetString("CStreamIOSendingTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streamIO =&gt; connected: {0}; remote end point: {1}; receive buffer size: {2}; receive timeout: {3}.
        /// </summary>
        internal static string CStreamIOToString {
            get {
                return ResourceManager.GetString("CStreamIOToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trying to send an empty buffer.
        /// </summary>
        internal static string CStreamIOTryingToSendEmptyBuffer {
            get {
                return ResourceManager.GetString("CStreamIOTryingToSendEmptyBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting to receive a buffer with no specific size from {0}.
        /// </summary>
        internal static string CStreamIOWaitingMessage {
            get {
                return ResourceManager.GetString("CStreamIOWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 length buffer size given, can&apos;t receive any message.
        /// </summary>
        internal static string CStreamIOZeroLengthBufferGiven {
            get {
                return ResourceManager.GetString("CStreamIOZeroLengthBufferGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no open stream.
        /// </summary>
        internal static string CStreamNoOpenedStream {
            get {
                return ResourceManager.GetString("CStreamNoOpenedStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an empty buffer has been recived.
        /// </summary>
        internal static string CStreamReceivedEmptyBuffer {
            get {
                return ResourceManager.GetString("CStreamReceivedEmptyBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received string message of {0} characters from {1}.
        /// </summary>
        internal static string CStreamReceivedStringMessage {
            get {
                return ResourceManager.GetString("CStreamReceivedStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to receive timeout: {0}; receive buffer: {1}; send timeout: {2}; send buffer: {3}; ssl: {4}.
        /// </summary>
        internal static string CStreamSettingsBaseToString {
            get {
                return ResourceManager.GetString("CStreamSettingsBaseToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to header is {0} bytes long; use header: {1}.
        /// </summary>
        internal static string CStreamToString {
            get {
                return ResourceManager.GetString("CStreamToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting to receive a message from {0}.
        /// </summary>
        internal static string CStreamWaitingMessage {
            get {
                return ResourceManager.GetString("CStreamWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting to receive a message from {0}, timeout is {1} millisecond(s).
        /// </summary>
        internal static string CStreamWaitingMessageWithTimeout {
            get {
                return ResourceManager.GetString("CStreamWaitingMessageWithTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string GeneralFrom {
            get {
                return ResourceManager.GetString("GeneralFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid IP address {0}:{1}.
        /// </summary>
        internal static string GeneralInvalidIPAddress {
            get {
                return ResourceManager.GetString("GeneralInvalidIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string GeneralNO {
            get {
                return ResourceManager.GetString("GeneralNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no IP address available.
        /// </summary>
        internal static string GeneralNoAvailableIPAddress {
            get {
                return ResourceManager.GetString("GeneralNoAvailableIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not specified.
        /// </summary>
        internal static string GeneralNotSpecified {
            get {
                return ResourceManager.GetString("GeneralNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string GeneralUnknown {
            get {
                return ResourceManager.GetString("GeneralUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string GeneralYES {
            get {
                return ResourceManager.GetString("GeneralYES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection string.
        /// </summary>
        internal static string ODBCConnectionString {
            get {
                return ResourceManager.GetString("ODBCConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database {0} is till opened.
        /// </summary>
        internal static string ODBCDatabaseStillOpened {
            get {
                return ResourceManager.GetString("ODBCDatabaseStillOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to column name.
        /// </summary>
        internal static string ODBColumnName {
            get {
                return ResourceManager.GetString("ODBColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - client at {1} is disconnecting.
        /// </summary>
        internal static string ServerClientIsDisconnecting {
            get {
                return ResourceManager.GetString("ServerClientIsDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - data [{1}].
        /// </summary>
        internal static string ServerData {
            get {
                return ResourceManager.GetString("ServerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - fetch message exception.
        /// </summary>
        internal static string ServerFetchMessageException {
            get {
                return ResourceManager.GetString("ServerFetchMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - environment for client at {1} is ready.
        /// </summary>
        internal static string ServerListenerClientConnected {
            get {
                return ResourceManager.GetString("ServerListenerClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - client at {1} has been denied connection.
        /// </summary>
        internal static string ServerListenerClientConnectionDeclined {
            get {
                return ResourceManager.GetString("ServerListenerClientConnectionDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - server listener created reading port {1}.
        /// </summary>
        internal static string ServerListenerCreated {
            get {
                return ResourceManager.GetString("ServerListenerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - server failed to start.
        /// </summary>
        internal static string ServerListenerFailedToStart {
            get {
                return ResourceManager.GetString("ServerListenerFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - failed to start {1} thread for client at {2}.
        /// </summary>
        internal static string ServerListenerFailedToStartThread {
            get {
                return ResourceManager.GetString("ServerListenerFailedToStartThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - server has stopped.
        /// </summary>
        internal static string ServerListenerHasStopped {
            get {
                return ResourceManager.GetString("ServerListenerHasStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - server is shutting down.
        /// </summary>
        internal static string ServerListenerIsShuttingDown {
            get {
                return ResourceManager.GetString("ServerListenerIsShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTENER SERVER.
        /// </summary>
        internal static string ServerListenerName {
            get {
                return ResourceManager.GetString("ServerListenerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - server not allowed to start.
        /// </summary>
        internal static string ServerListenerNotAllowedToStart {
            get {
                return ResourceManager.GetString("ServerListenerNotAllowedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - server is not running.
        /// </summary>
        internal static string ServerListenerNotRunning {
            get {
                return ResourceManager.GetString("ServerListenerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - thread has stopped.
        /// </summary>
        internal static string ServerListenerThreadHasStopped {
            get {
                return ResourceManager.GetString("ServerListenerThreadHasStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - thread is stopping.
        /// </summary>
        internal static string ServerListenerThreadIsStopping {
            get {
                return ResourceManager.GetString("ServerListenerThreadIsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MESSAGE HIDDEN&gt;.
        /// </summary>
        internal static string ServerMessageHidden {
            get {
                return ResourceManager.GetString("ServerMessageHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NOT CONNECTED&gt;.
        /// </summary>
        internal static string ServerNotConnected {
            get {
                return ResourceManager.GetString("ServerNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STREAM SERVER PROCESSOR.
        /// </summary>
        internal static string ServerProcessorName {
            get {
                return ResourceManager.GetString("ServerProcessorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - thread has received command to stop.
        /// </summary>
        internal static string ServerReceivedStopOrder {
            get {
                return ResourceManager.GetString("ServerReceivedStopOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STREAM SERVER RECEIVER.
        /// </summary>
        internal static string ServerReceiverName {
            get {
                return ResourceManager.GetString("ServerReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - send failed.
        /// </summary>
        internal static string ServerSendFailed {
            get {
                return ResourceManager.GetString("ServerSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending notification to {0}{1}.
        /// </summary>
        internal static string ServerSendingNotification {
            get {
                return ResourceManager.GetString("ServerSendingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - message is empty, no reply to return.
        /// </summary>
        internal static string ServerSendNoReply {
            get {
                return ResourceManager.GetString("ServerSendNoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - message is empty, no request to send.
        /// </summary>
        internal static string ServerSendNoRequest {
            get {
                return ResourceManager.GetString("ServerSendNoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - send reply of {1} bytes.
        /// </summary>
        internal static string ServerSendReply {
            get {
                return ResourceManager.GetString("ServerSendReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - start processing request of {1} bytes.
        /// </summary>
        internal static string ServerStartProcessingRequest {
            get {
                return ResourceManager.GetString("ServerStartProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - thread did not stop after {1} seconds, forcing it to stop.
        /// </summary>
        internal static string ServerThreadNotStopped {
            get {
                return ResourceManager.GetString("ServerThreadNotStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - unknown non fatal error.
        /// </summary>
        internal static string ServerUnknownNonFatalError {
            get {
                return ResourceManager.GetString("ServerUnknownNonFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - no thread method to call.
        /// </summary>
        internal static string THreadNoMethodToCall {
            get {
                return ResourceManager.GetString("THreadNoMethodToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string ThreadNoName {
            get {
                return ResourceManager.GetString("ThreadNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - thread result: {1}.
        /// </summary>
        internal static string ThreadResult {
            get {
                return ResourceManager.GetString("ThreadResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thread.
        /// </summary>
        internal static string ThreadThread {
            get {
                return ResourceManager.GetString("ThreadThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activity {0} could not be added.
        /// </summary>
        internal static string UIActivityFailedAddingActivity {
            get {
                return ResourceManager.GetString("UIActivityFailedAddingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while processing activity{0}.
        /// </summary>
        internal static string UIActivityInsideActivity {
            get {
                return ResourceManager.GetString("UIActivityInsideActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIActivity =&gt; control: {0}; event: {1}; message: {2}; value: {3}.
        /// </summary>
        internal static string UIActivityToString {
            get {
                return ResourceManager.GetString("UIActivityToString", resourceCulture);
            }
        }
    }
}
